---
title: "Funktionen"
author: "Xuan Son Le"
date: "16/03/2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


######################################################################################

```{r (Log)-Likelihood Funktion}
loglike_vector <- function(X,y,beta) {
    
    eta <- t(X) %*% beta #

    exp_eta <- exp(eta) # 
    
    p <- exp_eta / (1 + exp_eta) # 
    
    result <- crossprod(y,eta) - sum(log(1 + exp(eta)))
    
    return(-result) 
}

loglike <- function(X,y,beta) {
    
    eta <- t(X) %*% beta #

    exp_eta <- exp(eta) # 
    
    p <- exp_eta / (1 + exp_eta) # 
    
    result <- sum(crossprod(y,eta) - sum(log(1 + exp(eta))))
    
    return(result) 
}


## Test the results ###################################
#y <- matrix(c(1,0,1), ncol = 1)
#X <- matrix(c(1,4,7,1,5,8,1,6,9,4,5,6,7,8,9), ncol = 5, byrow = TRUE)
beta <- rep(1, times = ncol(X))
eta <- X %*% beta
exp_eta <- exp(eta)
p <- exp_eta / (1 + exp_eta)
eta <- (X %*% beta)
t(y) %*% eta

t(X) %*% beta

# crossprod(y,eta)
# p <- exp(eta) / (1 + exp(eta))
# 
# loglike_1(beta)
# loglike(beta)
# - sum( t(y)%*%log(p) + (t(1-y))%*%(log(1 - p)) )
# - sum(-y*log(1 + exp(-(X%*%beta))) - (1-y)*log(1 + exp(X%*%beta)))
# -sum(y*(X %*% beta - log(1+exp(X %*% beta))) + (1-y)*(-log(1 + exp(X %*% beta))))


```


```{r Score Funktion}
score <- function(beta) {
    
    eta <- X %*% beta #

    exp_eta <- exp(eta) # 
    
    p <- exp_eta / (1 + exp_eta) # 
    
    result <- sum(crossprod((y - p), X))
    
    return(result)
}

logit.gr <- function(beta) {

    grad <- beta*0

    eta <- X %*% beta #

    exp_eta <- exp(eta) # 
    
    p <- exp_eta / (1 + exp_eta) # 
    
    for (k in 1:as.numeric(ncol(X))) { 
      grad[k] <- sum(X[,k] * (y - p))
      }
    
    return(-grad)
}
```


```{r Logit Modell}

logitModell <- function(beta) {
        
        eta <- X %*% beta

        exp_eta <- exp(eta)

        p <- exp_eta / (1 + exp_eta)
        
        result <- sum(crossprod(y,eta) - sum(log(1 + exp(eta))))
        
        return(-result) 
    }
    
    score <- function(beta) {

        grad <- beta*0
    
        eta <- X %*% beta #
    
        exp_eta <- exp(eta) # 
        
        p <- exp_eta / (1 + exp_eta) # 
        
        for (k in 1:as.numeric(ncol(X))) { 
          grad[k] <- sum(X[,k] * (y - p))
          }
        
        return(-grad) 
    }
    
# mle = optim(initial_beta, fn = logLikelihood, gr = logit.gr, method = "BFGS", 
#             control = list(trace = TRUE, maxit = 1000), hessian = TRUE)
#mle$par

#out = list(beta=mle$par,vcov=solve(mle$hessian),ll=2*mle$value)
```

```{r}

XFull <- (X)
betaFull <- rep(0, times = nrow(X))

XNull <- X
betaNull <- rep(0, times = nrow(X))

llSaturated <- loglike(X = XFull,
                       y = t(model.response(testModelFrame)),
                       beta = betaFull)

llNull <- loglike(X_Null,
                  y = model.response(testModelFrame), 
                  beta = betaNull)

nullDeviance <- 2*abs(llSaturated - llNull)
```
 
