---
title: "Logistic Regression"
author: "Xuan Son Le (4669361), Freie Universität Berlin"
date: "04/04/2018"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Logistic Regression}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This vignette contains an example of a binary logistic regression. 

**Data preparing**
```{r Preparing data}
#install.packages("logitModell")
library(logitModell)

testData <- read.csv("https://stats.idre.ucla.edu/stat/data/binary.csv")
testData <- testData[1:100,]
testData$rank <- factor(testData$rank)
testFormula <- as.formula("admit ~ gre + gpa + rank")
testModelFrame <- model.frame(admit ~ gre + gpa + rank, testData)

# Alternatively one can use the following code to test the result on another data set. This data set is default built in R.

# data(cats, package = "MASS")
# testData <- cats[1:100,]
# #testData$Sex <- factor(testData$Sex, labels = c(0,1))
# testFormula <- as.formula("Sex ~ Bwt + Hwt")
# testModelFrame <- model.frame(Sex ~ Bwt + Hwt, testData)
```
  
\newline  
**Fit binary logit model**  
```{r Fit logit model}
fittedLogModell <- logitMod(formula = testFormula, data = testData)
standardModell <- glm(formula = testFormula, data = testData, family = "binomial")

all(all.equal(standardModell$coefficients,
              as.numeric(fittedLogModell$coefficients),
              check.attributes = FALSE),
    all.equal(vcov(standardModell), 
              fittedLogModell$vcov,
              check.attributes = FALSE, tolerance = exp(-10)),
    all.equal(residuals(standardModell),
              as.numeric(fittedLogModell$devianceResidual),
              check.attributes = FALSE, tolerance = exp(-10)),
    all.equal(standardModell$df.residual, fittedLogModell$dfRes),
    all.equal(standardModell$df.null, fittedLogModell$dfNull))
```
  
  
**Print method** 
```{r Print method}
print(fittedLogModell)
```
  
  
**Summary method**  
```{r Summary method}
summary(fittedLogModell)
```
  
  
**Plot method**  
```{r Plot method}
plot(fittedLogModell)
plot(glm(formula = testFormula, data = testData, family = "binomial"))
```
